"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.uploads import get_uploaded_file
from insta485.views.user import show_user_profile
from insta485.views.followers import show_followers
from insta485.views.following import show_following
from insta485.views.posts import show_post
from insta485.views.explore import show_explore
from insta485.views.login import show_login
from insta485.views.create import show_create
from insta485.views.delete import show_delete
from insta485.views.edit import show_edit
from insta485.views.auth import check_auth
from insta485.views.password import show_password
from insta485.views.likes import update_likes
from insta485.views.comments import handle_comments
from insta485.views.posts_change import manage_posts
from insta485.views.log_out import log_out
from insta485.views.new_account import handle_account
from insta485.views.new_following import handle_following